/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 6.0.0   2016-10-08

The MIT License (MIT)
Copyright (c) 2009-2016 Atollic AB

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
******************************************************************************
*/

/* Includes */
#include <stddef.h>
#include "stm32l1xx.h"


/* Private typedef */
/* Private define  */
/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */


/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main(void)
{

	  RCC_AHBPeriphClockCmd(RCC_AHBPeriph_GPIOA, ENABLE);
	  RCC_AHBPeriphClockCmd(RCC_AHBPeriph_GPIOC, ENABLE);

	  GPIO_InitTypeDef gpioInitStruc;

	  // Nastavenie parametrov LED - Uloha1
	  gpioInitStruc.GPIO_Mode = GPIO_Mode_OUT;
	  gpioInitStruc.GPIO_OType = GPIO_OType_PP;
	  gpioInitStruc.GPIO_Pin = GPIO_Pin_5;
	  gpioInitStruc.GPIO_Speed = GPIO_Speed_400KHz;
	  gpioInitStruc.GPIO_PuPd = GPIO_PuPd_UP;

	  GPIO_Init(GPIOA, &gpioInitStruc);

	  // Uloha 1 - zapnut, vypnut LED + zmena stavu
  	  GPIO_SetBits(GPIOA,GPIO_Pin_5); // Zapne LED
  	  GPIO_ResetBits(GPIOA,GPIO_Pin_5); // Vypne LED
  	  GPIO_ToggleBits(GPIOA, GPIO_Pin_5);  //zmena stavu LED
  	  GPIO_ToggleBits(GPIOA, GPIO_Pin_5);
  	  GPIO_ToggleBits(GPIOA, GPIO_Pin_5);

  	  // Uloha 2 - parametre tlacidla
  	  gpioInitStruc.GPIO_Mode = GPIO_Mode_IN;
  	  gpioInitStruc.GPIO_Pin = GPIO_Pin_13;
  	  gpioInitStruc.GPIO_PuPd = GPIO_PuPd_UP;
  	  gpioInitStruc.GPIO_Speed = GPIO_Speed_40MHz;

  		GPIO_Init(GPIOC,&gpioInitStruc);

  		uint8_t buttonState;


  		/* Infinite loop */
  while (1)
  {
	  // Uloha 2 - stav tlacidla
	  /*buttonState = GPIO_ReadInputDataBit(GPIOC,GPIO_Pin_13);

	  if(buttonState == 0)
	  	  {
	  		GPIO_SetBits(GPIOA, GPIO_Pin_5);
	  	  }
	  	else
	  	{
	  		GPIO_ResetBits(GPIOA, GPIO_Pin_5);
	  	}*/

	  // Uloha 3 - blikanie LED
	  for(int i=0;i<1000000;i++)
		  GPIO_SetBits(GPIOA,GPIO_Pin_5); // Zapne LED
	  for(int i=0;i<1000000;i++)
		  GPIO_ResetBits(GPIOA,GPIO_Pin_5); // Vypne LED

	  // Uloha 3 - stav 0-1-0
	  /*if((buttonState == 0) )
	  	 {
		  for(int i=0;i<300000;i++){}
	  	 }
	  if((buttonState == 0) )
	  	 {
	  		 GPIO_ToggleBits(GPIOA, GPIO_Pin_5);
	  	 }*/
  }
  return 0;
}

#ifdef  USE_FULL_ASSERT

/**
  * @brief  Reports the name of the source file and the source line number
  *   where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t* file, uint32_t line)
{
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */

  /* Infinite loop */
  while (1)
  {
  }
}
#endif

/*
 * Minimal __assert_func used by the assert() macro
 * */
void __assert_func(const char *file, int line, const char *func, const char *failedexpr)
{
  while(1)
  {}
}

/*
 * Minimal __assert() uses __assert__func()
 * */
void __assert(const char *file, int line, const char *failedexpr)
{
   __assert_func (file, line, NULL, failedexpr);
}
